[workspace]
members = [
    "bin/mev",
    "mev-boost-rs",
    "mev-relay-rs",
    "mev-build-rs",
    "mev-rs",
]
default-members = ["bin/mev"]

# [patch."https://github.com/ralexstokes/beacon-api-client"]
# beacon-api-client = { path = "../beacon-api-client" }
