[package]
name = "mev-relay-rs"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
futures = "0.3.21"
async-trait = "0.1.53"
parking_lot = "0.12.1"
pin-project = "1.0.12"

thiserror = "1.0.30"
http = "0.2.7"
url = { version = "2.2.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }

ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "46ca1716f2b1651e59b8a565b5bbcadf6b052fa5" }
beacon-api-client = { git = "https://github.com/ralexstokes/beacon-api-client", rev = "53690a711e33614d59d4d44fb09762b4699e2a4e" }

mev-rs = { path = "../mev-rs" }
mev-build-rs = { path = "../mev-build-rs" }
